version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/orchestrator"
      - "/apps/web"
      - "/packages/content-model"
      - "/packages/core"
      - "/packages/design-system"
      - "/packages/schema"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-deps:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      github-actions-deps:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/orchestrator"
      - "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-deps:
        patterns: ["*"]
